### ISSUE TITLE
Permissions causing WP RestAPI to fail

### ISSUE THREAD

**Issue by derseitenschneider** [publishpress/PublishPress-Permissions#917]
Could be due to the newest WP release (6.3) this week but we had issues with the wordpress rest api yesterday. After some investigations we figured out it's the permissions plugin causing that. Every time we hit the rest api, we get a Error 500 back and the following error log:

![Screenshot 11-8-2023 09-25-53 (1)](https://github.com/publishpress/PublishPress-Permissions/assets/97043252/7ae2d046-c793-4fb6-9834-5f4383e65aad)

Thanks for looking into that since the plugin overall works pretty nice and we would like to stick with it.

Greetings
Brian

**Comment by derseitenschneider** [comment]
@agapetry Thanks for reaching out. The error message is too long for a screenshot, i copy it here:

[Thu Aug 24 08:12:26 2023] [php:error] [pid 28889] [client 77.58.86.0] [host beimich.de] PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /is/htdocs/wp13828974_RO2QURFPF8/www/wp-content/plugins/press-permit-core/classes/PublishPress/Permissions.php:471\nStack trace:\n#0 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-content/plugins/press-permit-core/classes/PublishPress/Permissions.php(471): serialize(Array)\n#1 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-content/plugins/press-permit-core/classes/PublishPress/Permissions.php(451): PublishPress\\Permissions-]supplementUserAllcaps(Object(PublishPress\\PermissionsUser))\n#2 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-content/plugins/press-permit-core/classes/PublishPress/PermissionsHooks.php(323): PublishPress\\Permissions-]refreshUserAllcaps()\n#3 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-content/plugins/press-permit-core/classes/PublishPress/PermissionsHooks.php(184): PublishPress\\PermissionsHooks-]actInitUser()\n#4 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/class-wp-hook.php(310): PublishPress\\PermissionsHooks-]actSetCurrentUser('')\n#5 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/class-wp-hook.php(334): WP_Hook-]apply_filters(NULL, Array)\n#6 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/plugin.php(517): WP_Hook-]do_action(Array)\n#7 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/pluggable.php(48): do_action('set_current_use...')\n#8 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/user.php(3628): wp_set_current_user(10)\n#9 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/pluggable.php(70): _wp_get_current_user()\n#10 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/pluggable.php(1163): wp_get_current_user()\n#11 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/rest-api/class-wp-rest-server.php(332): is_user_logged_in()\n#12 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/rest-api.php(418): WP_REST_Server-]serve_request('/wp/v2/users')\n#13 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/class-wp-hook.php(310): rest_api_loaded(Object(WP))\n#14 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/class-wp-hook.php(334): WP_Hook-]apply_filters('', Array)\n#15 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/plugin.php(565): WP_Hook-]do_action(Array)\n#16 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)\n#17 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/class-wp.php(779): WP-]parse_request('')\n#18 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-includes/functions.php(1335): WP-]main('')\n#19 /is/htdocs/wp13828974_RO2QURFPF8/www/wp-blog-header.php(16): wp()\n#20 /is/htdocs/wp13828974_RO2QURFPF8/www/index.php(17): require('/is/htdocs/wp13...')\n#21 {main}\n  thrown in /is/htdocs/wp13828974_RO2QURFPF8/www/wp-content/plugins/press-permit-core/classes/PublishPress/Permissions.php on line 471
